### ISSUE TITLE
Web app looks odd in firefox

### ISSUE THREAD

**Issue by mathematiguy** [clics/clics3#12]
Hi there,

I thought I would have a go building this project and running the web app in docker, and so far the result looks like this:

![image](https://user-images.githubusercontent.com/11322313/83824838-a7de0880-a72b-11ea-91af-e35a75115d74.png)

Is this what it's supposed to look like? Or am I doing something wrong. I am running it in firefox, but it seems to be missing something.

**Comment by LinguList** [comment]
What is it missing? This is the local web application. If you cannot browse the networks, you need to open the HTML through a server, to circumvent firefox' new security restrictions with respect to ajax requests.

**Comment by mathematiguy** [comment]
Interesting, I am running it at localhost on my own machine (so I have admin rights). I guess the only weird problem in that case is the way the map isn't centered, unless it is supposed to look like that.

I mainly raised this issue to check if my attempt to get the CLICS browser running locally was successful. If that seems to be the case to you, feel free to close this issue.

**Comment by xrotwang** [comment]
Once you have selected a cluster, the location of the map shouldn't look
that much out of place, I think, but rather aligned with the bottom edge of
the graph.

Caleb Moses <notifications@github.com> schrieb am Fr., 5. Juni 2020, 09:35:

**Comment by LinguList** [comment]
Check also [this version online](https://digling.org/calc/clics/). This is how it is supposed to look.
