### ISSUE TITLE
Python 3.10 workflow errors

### ISSUE THREAD

**Issue by M0nochrome** [clics/clics3#26]
Seems like I have a problem getting past step 6. Upon entering the command

`clics --seed 42 -t 3 -f families makeapp`

I get the error: UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 672: character maps to <undefined>

![2024-08-10 17_02_53-C__WINDOWS_system32_cmd exe](https://github.com/user-attachments/assets/e9543a42-5917-4df8-a34e-9876c597231a)

I had similar problems in step 5 as well (encoding error there too) but I just downloaded the network-3-families.gml file

**Comment by LinguList** [comment]
Do you have the chance to test in non-windows? Windows now offers a direct Ubuntu integration. The error is that by default, Windows seems to assume a non-Unicode encoding. 

Alternatively, can you fix in your clicks_env directly?

Try to replace [this](https://github.com/clics/pyclics/blob/4fcaa7e318025e4fcf568831f5329db7cbcb1708/src/pyclics/models.py#L110C1-L115C46):

```python
    @property
    def graph(self):
        def lines():
            for line in self.fname.open():
                yield line.encode('ascii', 'xmlcharrefreplace').decode('utf-8')
        return nx.parse_gml(''.join(lines()))
```

by

```python
    @property
    def graph(self):
        def lines():
            for line in self.fname.open(coding="utf-8"): # try also coding="ascii"
                yield line.encode('ascii', 'xmlcharrefreplace').decode('utf-8')
        return nx.parse_gml(''.join(lines()))
```

**Comment by LinguList** [comment]
The `coding="xyz"`-attribute is probably having a different default in windows that causes the code error. But I cannot directly tell what we need, either "utf-8" or "ascii" would be my guess (I am not good at this, typically try out until I find a solution).

**Comment by M0nochrome** [comment]
You were right. I switched to the Ubuntu bash under windows and everything ran fine.
The only problem I had was in step 4 where I had to break it in two loads, cause running it as is it produced some errors (forgot to screenshot).
