### ISSUE TITLE
What goes into the CLICS dataset?

### ISSUE THREAD

**Issue by xrotwang** [clics/clics3#3]
- [x] the network (see #39 )
- [x] the lexical data - augmented with CLICS value - as CLDF Wordlist
- [x] the sqlite database - since its use is described in the [cookbook](https://github.com/clics/clics2/tree/master/cookbook#the-clics-sqlite-database)?

**Comment by LinguList** [comment]
Yes, I guess this makes sense, with sqlite.

**Comment by Anaphory** [comment]
Without knowing your exact model, I would expect an SQLite db (in particular one that is automatically generated and redundant with other data) to be part of a release, just like a pre-compiled binary for a software project, but not actually part of the version-tracked repository. I think it could be part of a Zenodo release, though, but I don't know how that would be cleanly achieved.
