### ISSUE TITLE
Release all datasets with pylexibank 2.0

### ISSUE THREAD

**Issue by xrotwang** [clics/clics3#5]
While this may be a bit stressful, I think it's worth it. Otherwise we'd release something that's basically not dead, but EOL on arrival.

**Comment by LinguList** [comment]
Yes, given the reviews we received, we should take this as a gentle push to get things finalized. @chrzyki, when starting to organize things, we should also make a list of the datasets who finalizes them.

**Comment by chrzyki** [comment]
Done
