### ISSUE TITLE
Update Code Ocean Capsule

### ISSUE THREAD

**Issue by chrzyki** [clics/clics3#6]
This involves:

- updated `pyclics`, `pylexibank` and dependencies
- update datasets

**Comment by chrzyki** [comment]
Updated capsule has been submitted, will close once it is published.

**Comment by xrotwang** [comment]
But this repos can be released anyway, right?

**Comment by chrzyki** [comment]
Yes

On 13 Nov 2019 14:09, Robert Forkel <notifications@github.com> wrote:

But this repos can be released anyway, right?

**Comment by chrzyki** [comment]
Done

- https://codeocean.com/capsule/7201165/
- https://doi.org/10.24433/CO.4564348.v2
